#! /usr/bin/env ansible-playbook
# Uninstall role
# Run prior to removing host from inventory groups, so hostvars are accessible
---
- name: bird | uninstall
  hosts: bgp
  tasks:
  - include_role:
      name: bird
      tasks_from: uninstall.yml
